name: Deploy to Heroku

on:
  workflow_run:
    workflows: [ "Node.js CI" ]
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "commander-hub-staging"
          heroku_email: "thestandardmodelofromagna@gmail.com"
  
  discord_message:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_UPDATE_WEBHOOK }}
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed to production environment as: .'