name: Deploy to Heroku

on:
  workflow_run:
    workflows: [ "Node.js CI" ]
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "commander-hub-staging"
          heroku_email: "thestandardmodelofromagna@gmail.com"
  
  discord_message:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub Bot"
          message: "The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed to production environment as: ."
